/* GENERATED by tools/build-blog.mjs from blog/ — do not edit by hand. */
window.NK = window.NK || {};
NK.posts = [
 {
  "slug": "hello-world",
  "title": "Hello, World",
  "date": "2026-09-24",
  "tags": [
   "meta",
   "portfolio"
  ],
  "summary": "Why this portfolio is a terminal, and what I'll write about here.",
  "folder": "notes",
  "placeholder": true,
  "draft": false,
  "links": [
   "pluto",
   "go-ascii-streamer",
   "printsmithz"
  ],
  "body": "> [!todo] Placeholder\n> This is sample content. Replace it with your own note in Obsidian — it syncs here automatically once the GitHub workflow is on.\n\nI'm Nikhil. I build ==systems that run themselves==, robots that pull weeds, and printed parts you can hold.\n\nThis blog is my Obsidian vault, published. Notes link to each other the same way they do in my editor, so start anywhere:\n\n- [[pluto]] — the weed-removing robot that won a best-paper award\n- [[go-ascii-streamer]] — streaming video into a terminal as text\n- [[printsmithz]] — running a tiny 3D-printing studio\n\n## Why a terminal?\n\nBecause it's the interface I trust most. Every button on the homepage runs a real command, so you can see exactly what happened — `ls`, `cd`, `cat`.\n\n## What to expect\n\n1. Build logs from projects, warts included\n2. Short notes on things I learned the hard way\n3. The occasional #eindhoven life update"
 },
 {
  "slug": "pluto",
  "title": "Pluto — an autonomous weed-removing robot",
  "date": "2026-09-20",
  "tags": [
   "robotics",
   "ai",
   "project"
  ],
  "summary": "How Pluto finds weeds and removes them, and what won it Best Paper.",
  "folder": "projects",
  "placeholder": true,
  "draft": false,
  "links": [
   "hello-world"
  ],
  "body": "> [!todo] Placeholder\n> Outline only. Fill in the real story, photos and numbers.\n\n## The problem\n\nDescribe the field, the weeds, and why manual removal doesn't scale.\n\n## How it works\n\n| Stage | What happens |\n|---|---|\n| Sense | Camera frames → weed detection |\n| Decide | Pick targets, plan a path |\n| Act | Remove the weed, move on |\n\n## What I learned\n\n- [ ] Add one surprising failure\n- [ ] Add one metric you're proud of\n- [x] Won Best Paper\n\nRelated: [[hello-world]] · #robotics"
 },
 {
  "slug": "go-ascii-streamer",
  "title": "Go-ASCII-Streamer",
  "date": "2026-09-12",
  "tags": [
   "go",
   "project"
  ],
  "summary": "Streaming live video into the terminal as ASCII, frame by frame.",
  "folder": "projects",
  "placeholder": true,
  "draft": false,
  "links": [
   "hello-world"
  ],
  "body": "> [!todo] Placeholder\n> Swap this for your build log.\n\nEvery frame becomes a grid of characters. Brighter pixels get denser glyphs:\n\n```go\nconst ramp = \" .:-=+*#%@\"\n\nfunc toASCII(lum float64) byte {\n    return ramp[int(lum*float64(len(ramp)-1))]\n}\n```\n\n> [!tip] Why Go?\n> Goroutines make the capture → convert → send pipeline trivial to parallelise.\n\nBack to [[hello-world]]."
 }
];
