#!/usr/bin/env node
// Builds js/posts.js from the Obsidian notes in blog/ (no dependencies).
//   node tools/build-blog.mjs
// Skips: templates/, .obsidian/, files starting with "_" and notes with `draft: true`.
// Run locally, or let .github/workflows/blog.yml run it on every push.
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const vault = join(root, "blog");
const slugify = (s) => String(s).toLowerCase().trim().replace(/\.md$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function walk(dir) {
  return readdirSync(dir).flatMap((n) => {
    if (n.startsWith(".") || n.startsWith("_") || n === "templates") return [];
    const p = join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : n.endsWith(".md") ? [p] : [];
  });
}

function frontmatter(src) {
  const m = src.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) return [{}, src];
  const data = {};
  let key = null;
  for (const line of m[1].split(/\r?\n/)) {
    const li = line.match(/^\s+-\s+(.*)$/);
    if (li && key) { (data[key] = Array.isArray(data[key]) ? data[key] : []).push(li[1].trim().replace(/^["']|["']$/g, "")); continue; }
    const kv = line.match(/^([\w-]+):\s*(.*)$/);
    if (!kv) continue;
    key = kv[1];
    let v = kv[2].trim();
    if (/^\[.*\]$/.test(v)) v = v.slice(1, -1).split(",").map((x) => x.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
    else if (v === "true" || v === "false") v = v === "true";
    else v = v.replace(/^["']|["']$/g, "");
    data[key] = v === "" ? [] : v;
  }
  return [data, src.slice(m[0].length)];
}

const posts = walk(vault).map((file) => {
  const [fm, body] = frontmatter(readFileSync(file, "utf8"));
  const slug = slugify(fm.slug || basename(file));
  const links = [...body.matchAll(/\[\[([^\]|#]+)/g)].map((m) => slugify(m[1]));
  const firstPara = body.split(/\n\s*\n/).find((b) => b.trim() && !/^[#>|`-]/.test(b.trim())) || "";
  return {
    slug,
    title: fm.title || basename(file, ".md"),
    date: fm.date || statSync(file).mtime.toISOString().slice(0, 10),
    tags: Array.isArray(fm.tags) ? fm.tags : fm.tags ? [fm.tags] : [],
    summary: fm.summary || firstPara.replace(/\s+/g, " ").slice(0, 160),
    folder: relative(vault, dirname(file)).replace(/\\/g, "/"),
    placeholder: !!fm.placeholder,
    draft: !!fm.draft,
    links: [...new Set(links)],
    body: body.trim()
  };
}).filter((p) => !p.draft).sort((a, b) => (a.date < b.date ? 1 : -1));

const out = `/* GENERATED by tools/build-blog.mjs from blog/ — do not edit by hand. */
window.NK = window.NK || {};
NK.posts = ${JSON.stringify(posts, null, 1)};
`;
writeFileSync(join(root, "js", "posts.js"), out);
console.log(`blog: ${posts.length} post(s) → js/posts.js`);
